apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backstage.fullname" . }}-config
  labels:
    {{- include "backstage.labels" . | nindent 4 }}
data:
  app-config.cluster.yaml: |
    app:
      baseUrl: {{ .Values.env.BACKSTAGE_BASE_URL }}

    backend:
      baseUrl: {{ .Values.env.BACKSTAGE_BASE_URL }}
      cors:
        origin: {{ .Values.env.BACKSTAGE_BASE_URL }}

    auth:
      environment: production
      providers:
        {{- if .Values.auth.allowGuest }}
        guest:
          dangerouslyAllowOutsideDevelopment: true
        {{- end }}

    catalog:
      locations:
        - type: url
          target: https://github.com/nielsreloeraw/backstage/blob/main/backstage/entities/all.yaml
        - type: url
          target: https://github.com/nielsreloeraw/backstage/blob/main/backstage/templates/all.yaml
