apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: john
spec:
  memberOf: [auth]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: mark
spec:
  memberOf: [auth]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: claire
spec:
  memberOf: [video]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: susan
spec:
  memberOf: [audio]